execute_process(COMMAND "${PROBE}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status STREQUAL "2" OR NOT error MATCHES "Usage: ngx-probe")
    message(FATAL_ERROR "Missing arguments did not produce usage exit 2: ${status}: ${error}")
endif()
execute_process(COMMAND "${PROBE}" no-such-runtime no-output Z RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status STREQUAL "1" OR NOT error MATCHES "Preset must be")
    message(FATAL_ERROR "Invalid preset did not fail before GPU/runtime access: ${status}: ${error}")
endif()
execute_process(COMMAND "${PROBE}" no-such-runtime no-output K --bridge-super-resolution RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status STREQUAL "1" OR NOT error MATCHES "Missing runtime DLL")
    message(FATAL_ERROR "SR option did not validate runtime before GPU access: ${status}: ${error}")
endif()
execute_process(COMMAND "${PROBE}" no-such-runtime no-output K --unknown RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status STREQUAL "2")
    message(FATAL_ERROR "Unknown probe option was accepted: ${status}: ${error}")
endif()
